[build-system]
requires = ["setuptools (>=67,<70)", "wheel", "setuptools_scm"] # setuptools limited for use of pkg_resources API
build-backend = "setuptools.build_meta"

[project]
name = "cube4health"
description = "Package cube4health is a data acquisition, processing, and publishing toolkit designed to streamline the integration of health, climate, and drone imagery data from Brazil and any other country adhering to standardized protocols. It enables the efficient handling of heterogeneous data sources into a unified structure, supporting scalable workflows for data ingestion, transformation, and dissemination."
readme = "README.rst"
authors = [
  {name = "Adeline Maciel", email = "adelinemaciel22@gmail.com"},
  {name = "Marcos Lima Rodrigues", email = "marcos.mlr@gmail.com"},
  {name = "Yuri Domaradzki", email = "yuridomaradzki@gmail.com"}
]
maintainers = [
  {name = "Adeline Maciel", email = "adelinemaciel22@gmail.com"},
  {name = "Gabriel Sansigolo", email = "gabrielsansigolo@gmail.com"},
  {name = "Luana Becker", email = "luanabeckerdaluz@gmail.com"},
  {name = "Marcos Lima Rodrigues", email = "marcos.mlr@gmail.com"},
  {name = "Yuri Domaradzki", email = "yuridomaradzki@gmail.com"}
]
classifiers = [
  "Programming Language :: Python :: 3",
  "Operating System :: Linux Ubuntu",

]
license = {text = "GNU General Public License v3"}
requires-python = ">= 3.10"

dependencies = [
  "requests",
  "geobr",
  "pandas",
  "geopandas",
  "tqdm",
  "python-dateutil",
  "fiona",
  "shapely",
  "psutil",
  "fastparquet",
  "pyarrow",
  "bdc-catalog @ git+https://github.com/Harmonize-Brazil/bdc-catalog.git@master",
  "bdc-db @ git+https://github.com/brazil-data-cube/bdc-db@v0.6.3",
  "geoserver-rest @ git+https://github.com/YuriDomaradzki/geoserver-rest.git@dev",
  "geoserver-restconfig @ git+https://github.com/Harmonize-Brazil/geoserver-restconfig",
  "paramiko",
  "jsonpath_rw",
  "psycopg2-binary",
  "psycopg2",
  "rasterio",
  "geoalchemy2",
  "flask",
  "docker",
  "matplotlib",
  "affine",
  "geopy",
  "jsonpath_rw_ext",
  "pytz",
  "timezonefinder[pytz]",
  "defusedxml",
  "opencv-python",
  "tqdm",
  "click",
  "attrs",
  "branca",
  "cdsapi",
  "certifi",
  "cffi",
  "cfgrib",
  "cftime",
  "charset-normalizer",
  "click-plugins",
  "cligj",
  "contourpy",
  "cycler",
  "datapi",
  "eccodes",
  "epiweeks",
  "et-xmlfile",
  "findlibs",
  "folium",
  "fonttools",
  "greenlet",
  "h5netcdf",
  "h5py",
  "html5lib",
  "idna",
  "jinja2",
  "kiwisolver",
  "lxml",
  "markupsafe",
  "multiurl",
  "natsort",
  "netcdf4",
  "openpyxl",
  "packaging",
  "pillow",
  "pycparser",
  "pyogrio",
  "pyparsing",
  "pyproj",
  "rioxarray",
  "six",
  "sqlalchemy",
  "typing-extensions",
  "tzdata",
  "unidecode",
  "urllib3",
  "webencodings",
  "xarray",
  "xyzservices"
]

dynamic = ["version"]
[tool.setuptools_scm]
version_file = "src/cube4health/__init__.py"

# Extras Dependencies
[project.optional-dependencies]
dev = [
    "coverage",  # testing
    "mypy",  # linting
    "pytest",  # testing
    "ruff"  # linting
]
docs = [
    "Sphinx>=7.0",
    "sphinx_rtd_theme",
    "sphinx-copybutton",
    "sphinx-tabs",
]
tests = [
    "coverage>=6.4",
    "coveralls>=3.3",
    "pytest>=7.4",
    "pytest-cov>=4.1",
    "pytest-pep8>=1.0",
    "pydocstyle>=4.0",
    "isort>4.3",
    "check-manifest>=0.40",
]
all = ["cube4health[docs,tests]"]
## End extras dependencies

[project.urls]
bugs = "https://github.com/Harmonize-Brazil/cube4health/issues"
changelog = "https://github.com/Harmonize-Brazil/cube4health/blob/master/changelog.md"
homepage = "https://github.com/Harmonize-Brazil/cube4health"

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
"*" = ["*.*"]

[project.scripts]
cube4health = "cube4health.cli:cli"


# Mypy
# ----

[tool.mypy]
files = "."

# Use strict defaults
strict = true
warn_unreachable = true
warn_no_return = true

[[tool.mypy.overrides]]
# Don't require test functions to include types
module = "tests.*"
allow_untyped_defs = true
disable_error_code = "attr-defined"